### PR TITLE
Fixed subnet allocation in case of etcd manager with IPv6

### PR DESCRIPTION
**Pull request by rbrtbnfgl**
## Description

Fix the subnet allocation in case of etcd when using IPv6 #1580 #1581 

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Review by pranavadn — COMMENTED** [review]
Does sn6.IP.Cmp(config.IPv6SubnetMax) < 0 comparison not exclude the last subnet? This was also an issue in the original code that raised with 1581. It should be like the v4 comparison sn.IP <= config.SubnetMax.

**Comment by rbrtbnfgl** [comment]
yes you are right, I thought that it was the first not acceptable IP but it is the latest. I'll fix it.

**Comment by pranavadn** [comment]
Looks good to me. Please go ahead and merge.

**Comment by pranavadn** [comment]
@rbrtbnfgl @manuelbuil Could we please get 0.18.2 image with these fixes?

**Review by pranavadn — APPROVED** [review]
Looks fine to me.

**Review by pranavadn — APPROVED** [review]

**Pull request merged**
