### PR TITLE
add mips64le support

### PR DESCRIPTION
**Pull request by lina-not-linus**
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by lina-not-linus** [comment]
Added mips64 support,The compilation on mips64 is verified and runs successfully.

**Comment by rajatchopra** [comment]
/lgtm
@arasananbu PTAL

**Comment by scott0000** [comment]
@lina-not-linus hello, the image "mips64le/busybox:glibc" seems not to be public . how can I get the this image? thks

**Comment by scott0000** [comment]
@rajatchopra  @lina-not-linus can this PR be merged ?

**Comment by rajatchopra** [comment]
@lina-not-linus Sorry about the delay. Can we please rebase this.

**Comment by lina-not-linus** [comment]
That would be fine. Thank you very much
Thanks

Rajat Chopra <notifications@github.com> 于 2020年10月15日周四 23:56写道：

**Comment by zhangguanzhang** [comment]
any update?

**Comment by jiangxiaobin96** [comment]
When wget `qemu-mips64le-static`, can download the correct package. Because I only find [qemu-mips64el-static](https://github.com/multiarch/qemu-user-static/releases/download/v6.1.0-8/qemu-mips64el-static). 
So I think it may be necessary to modify the `dist/qemu-%-static:` and add `elif ... then...`

**Comment by manuelbuil** [comment]
@lina-not-linus is this PR still important? I am trying to clean-up things a bit in the flannel project. If it is, let's try to merge it (after rebasing)

**Comment by luthermonson** [comment]
@jiangxiaobin96 we would like this merged, could you rebase and we will get it through

**Comment by jiangxiaobin96** [comment]
> @jiangxiaobin96 we would like this merged, could you rebase and we will get it through

please check [#1526](https://github.com/flannel-io/flannel/pull/1526) for rebase.

**Comment by manuelbuil** [comment]
We continue on https://github.com/flannel-io/flannel/pull/1526

**Pull request closed without merging**
