### PR TITLE
Removed dirty flag

### PR DESCRIPTION
**Pull request by rbrtbnfgl**
## Description

Remove dirty flag from the command that generates the TAG
## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by manuelbuil** [comment]
Is dirty flag adding dirty when it detects something in the git index?

**Comment by rbrtbnfgl** [comment]
yes

**Comment by manuelbuil** [comment]
did you find out why was something in the git index and not merged?

**Comment by rbrtbnfgl** [comment]
we modify some files during the release. I don't know why we are getting the dirty flag now and not on the previous release.

**Pull request merged**
