### PR TITLE
Add tencent cloud VPC network support

### PR DESCRIPTION
**Pull request by dragonorloong**
New feature:

Add tencent cloud VPC network support

## Release Note

```release-note
None required
```

### CODE REVIEW

**Comment by luthermonson** [comment]
@dragonorloong any way you can show tests for this working in tencent cloud? we'd like to merge this but we dont really have any good way to show this working. maybe join one of our community meetings and walk us through it?  https://github.com/coreos/flannel#community-meeting

**Comment by dragonorloong** [comment]
测试步骤：
1. 创建vpc:
image

2. 创建两台虚拟机
3.

**Comment by luthermonson** [comment]
@dragonorloong can you fix the go fmt issues in the build and we'll get this merged. thanks

**Comment by dragonorloong** [comment]
@luthermonson, I have fixed conflicts and formatting issues

**Review by luthermonson — APPROVED** [review]
approved but we gotta figure out why travis stopped working... i will merge as soon as we get another run of ci on this

**Comment by luthermonson** [comment]
@dragonorloong can you force push something to this branch to see if travis kicks in, i reactivated it for the new org

**Comment by dragonorloong** [comment]
> @dragonorloong您可以强制向此分支推送内容以查看travis是否启动，我已为新组织重新激活了它

@luthermonson done

**Comment by dragonorloong** [comment]
> @dragonorloong can you force push something to this branch to see if travis kicks in, i reactivated it for the new org

@luthermonson  done

**Review by rajatchopra — APPROVED** [review]
/lgtm

Thanks for the work.

**Pull request merged**
