### PR TITLE
host-gw (linux): Add dual stack support

### PR DESCRIPTION
**Pull request by yuanying**
## Description

Add dual stack support to host-gw backend. Currently only work with
linux now. Other limitations are the same as for the vxlan backend.

## Todos
- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
Dual-stack support for flannel with host-gw backend
```

### CODE REVIEW

**Review by manuelbuil — APPROVED** [review]
The route_network.go is a bit unorganized. I prefer if receiver functions are grouped together and not mixed with regular functions but I guess that's my taste

**Comment by yuanying** [comment]
@manuelbuil Thanks for your review! I fixed to use receiver function. If it's ok, I'll amend it to the original commit.

**Comment by manuelbuil** [comment]
LGTM! Let us merge https://github.com/flannel-io/flannel/pull/1469 first to make sure we don't introduce any regressions

**Comment by manuelbuil** [comment]
Please rebase!

**Comment by yuanying** [comment]
Done!

**Pull request merged**
